- generateResources.py
- src/main/java/net/dries007/tfc/TerraFirmaCraft.java
- src/main/java/net/dries007/tfc/api/recipes/LoomRecipe.java
- src/main/java/net/dries007/tfc/api/registries/TFCRegistries.java
- src/main/java/net/dries007/tfc/api/registries/TFCRegistryNames.java
- src/main/java/net/dries007/tfc/client/ClientRegisterEvents.java
- src/main/java/net/dries007/tfc/client/render/TESRBase.java
- src/main/java/net/dries007/tfc/client/render/TESRBellows.java
- src/main/java/net/dries007/tfc/client/render/TESRLoom.java
- src/main/java/net/dries007/tfc/network/PacketBellowsUpdate.java
- src/main/java/net/dries007/tfc/network/PacketLoomUpdate.java
- src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java
- src/main/java/net/dries007/tfc/objects/blocks/wood/BlockLoom.java
- src/main/java/net/dries007/tfc/objects/items/ItemAnimalHide.java
- src/main/java/net/dries007/tfc/objects/items/ItemCraftingTool.java
- src/main/java/net/dries007/tfc/objects/items/ItemsTFC.java
- src/main/java/net/dries007/tfc/objects/recipes/RecipeRegistryEvents.java
- src/main/java/net/dries007/tfc/objects/recipes/ShapelessDamageAddItemRecipe.java
- src/main/java/net/dries007/tfc/objects/recipes/UnmoldRecipe.java
- src/main/java/net/dries007/tfc/objects/te/TEBellows.java
- src/main/java/net/dries007/tfc/objects/te/TELoom.java
- src/main/java/net/dries007/tfc/types/DefaultRecipes.java
- src/main/java/net/dries007/tfc/types/Registries.java
- src/main/java/net/dries007/tfc/util/IFireable.java
- Loom and its items
- Fixed saw recipes
- Fixed unmold recipes only giving items on closing inventory
- Can't remember more...
> Loom n stuff

- generateResources.py
- src/main/java/net/dries007/tfc/ConfigTFC.java
- src/main/java/net/dries007/tfc/TerraFirmaCraft.java
- src/main/java/net/dries007/tfc/api/recipes/LoomRecipe.java
- src/main/java/net/dries007/tfc/api/types/Rock.java
- src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java
- src/main/java/net/dries007/tfc/objects/blocks/metal/BlockAnvilTFC.java
- src/main/java/net/dries007/tfc/objects/blocks/stone/BlockRockRaw.java
- src/main/java/net/dries007/tfc/objects/blocks/stone/BlockRockVariant.java
- src/main/java/net/dries007/tfc/objects/blocks/stone/BlockRockVariantFallable.java
- src/main/java/net/dries007/tfc/objects/blocks/stone/BlockStoneAnvil.java
- src/main/java/net/dries007/tfc/objects/blocks/wood/BlockLeavesTFC.java
- src/main/java/net/dries007/tfc/objects/blocks/wood/BlockSupport.java
- src/main/java/net/dries007/tfc/objects/te/TEAnvilTFC.java
- src/main/java/net/dries007/tfc/objects/te/TEBellows.java
- src/main/java/net/dries007/tfc/objects/te/TELoom.java
- src/main/java/net/dries007/tfc/util/ICollapsableBlock.java
- src/main/java/net/dries007/tfc/util/IFallingBlock.java
- src/main/java/net/dries007/tfc/util/TFCSoundEvents.java
Support beams can support IFallingBlock and ICollapsable(from extending base interface)
Raw rock collapse logic needs tweak, let's discuss that in discord.
Support beam models could use some rework from someone more experienced than me, the textures looks stretched :/
> Added support beams, made raw rock collapsable, imported TFC-Classic sound effects

- src/main/java/net/dries007/tfc/objects/blocks/BlockFireBrick.java
- src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java
- src/main/java/net/dries007/tfc/objects/blocks/devices/BlockBlastFurnace.java
- src/main/java/net/dries007/tfc/objects/blocks/wood/BlockSupport.java
- src/main/java/net/dries007/tfc/objects/items/ItemsTFC.java
- src/main/java/net/dries007/tfc/objects/te/TEPitKiln.java
- src/main/java/net/dries007/tfc/types/DefaultRecipes.java
- src/main/java/net/dries007/tfc/util/ICollapsableBlock.java
- src/main/java/net/dries007/tfc/util/TFCSoundEvents.java
Less cpu cycles for better performance :1st_place_medal:
> Collapse mechanics refinement + Fire clay features

- src/main/java/net/dries007/tfc/client/render/TESRPitKiln.java
- src/main/java/net/dries007/tfc/client/render/TESRPlacedItem.java
- src/main/java/net/dries007/tfc/client/render/TESRQuern.java
- src/main/java/net/dries007/tfc/objects/recipes/RecipeUtils.java
- src/main/java/net/dries007/tfc/objects/recipes/ShapedDamageRecipe.java
- src/main/java/net/dries007/tfc/objects/te/TEPlacedItem.java
Fixed issue #157 
Fixed issue #137 
Fixed issue #63 
- Stone tools can use bone as tool rod
> Pit kiln and placed item rendering fix + quern rendering fix

- src/main/java/net/dries007/tfc/TerraFirmaCraft.java
- src/main/java/net/dries007/tfc/client/render/animal/RenderAnimalTFCFamiliarity.java
Added animals familiarity render like TFC-Classic.
> Added animals familiarity render

- generateResources.py
- src/main/java/net/dries007/tfc/TerraFirmaCraft.java
- src/main/java/net/dries007/tfc/api/types/IBerryBush.java
- src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java
- src/main/java/net/dries007/tfc/objects/blocks/agriculture/BlockBerryBush.java
- src/main/java/net/dries007/tfc/objects/blocks/agriculture/BlockFruitTreeBranch.java
- src/main/java/net/dries007/tfc/util/agriculture/BerryBush.java
- src/main/java/net/dries007/tfc/world/classic/worldgen/WorldGenBerryBushes.java
> Berry Bushes

- src/main/java/net/dries007/tfc/client/model/animal/ModelDeerTFC.java
fix model and textures
Fixes #193
> Fix #193, Z-fighting on deer

- src/main/java/net/dries007/tfc/client/TFCSoundEvents.java
- src/main/java/net/dries007/tfc/objects/blocks/BlockCharcoalPile.java
Had to change how the charcoal SoundEvents are registered from the rest because the SoundType needs them to be fully initialized
> Added custom charcoal pile sounds

- generateResources.py
- src/main/java/net/dries007/tfc/client/ClientEvents.java
- src/main/java/net/dries007/tfc/client/model/animal/ModelRabbitTFC.java
- src/main/java/net/dries007/tfc/client/render/animal/RenderRabbitTFC.java
- src/main/java/net/dries007/tfc/objects/entity/EntitiesTFC.java
- src/main/java/net/dries007/tfc/objects/entity/animal/EntityRabbitTFC.java
- src/main/java/net/dries007/tfc/util/LootTableListTFC.java
- src/main/java/net/dries007/tfc/util/agriculture/Food.java
- src/main/java/net/dries007/tfc/world/classic/biomes/BiomeTFC.java
Added Rabbits, using vanilla textures and model. No Killer-rabbit (skin pick chance), all rabbits types the same, differ only in texture.
> Added Rabbits

- generateResources.py
- src/main/java/net/dries007/tfc/client/ClientEvents.java
- src/main/java/net/dries007/tfc/client/model/animal/ModelWolfTFC.java
- src/main/java/net/dries007/tfc/client/render/animal/LayerWolfCollarTFC.java
- src/main/java/net/dries007/tfc/client/render/animal/RenderWolfTFC.java
- src/main/java/net/dries007/tfc/objects/entity/EntitiesTFC.java
- src/main/java/net/dries007/tfc/objects/entity/IEntityOwnableTFC.java
- src/main/java/net/dries007/tfc/objects/entity/ai/EntityAIBegTFC.java
- src/main/java/net/dries007/tfc/objects/entity/ai/EntityAIFollowOwnerTFC.java
- src/main/java/net/dries007/tfc/objects/entity/ai/EntityAIOwnerHurtByTargetTFC.java
- src/main/java/net/dries007/tfc/objects/entity/ai/EntityAIOwnerHurtTargetTFC.java
- src/main/java/net/dries007/tfc/objects/entity/ai/EntityAISitTFC.java
- src/main/java/net/dries007/tfc/objects/entity/ai/EntityAITargetNonTamedTFC.java
- src/main/java/net/dries007/tfc/objects/entity/animal/EntityTameableTFC.java
- src/main/java/net/dries007/tfc/objects/entity/animal/EntityWolfTFC.java
- src/main/java/net/dries007/tfc/util/LootTableListTFC.java
- src/main/java/net/dries007/tfc/util/agriculture/Food.java
- src/main/java/net/dries007/tfc/world/classic/biomes/BiomeTFC.java
Vanilla like tameable Wolfs, extends TFC EntityAnimalMammal, can be tamed if Familiarity >= some value (0.3 now).
> Added Wolfs

- src/main/java/net/dries007/tfc/TerraFirmaCraft.java
- src/main/java/net/dries007/tfc/objects/blocks/agriculture/BlockFruitTreeLeaves.java
- src/main/java/net/dries007/tfc/world/classic/worldgen/WorldGenFissure.java
Closes #51 
I'm certain that this won't cause cascading lag, but could use more tweaking on rock placement logic. I'm leaving the old method there disabled for anything.
> Rework on fissure generation

- src/main/java/net/dries007/tfc/CommonEventHandler.java
- src/main/java/net/dries007/tfc/ConfigTFC.java
- src/main/java/net/dries007/tfc/TerraFirmaCraft.java
- src/main/java/net/dries007/tfc/api/capability/food/FoodStatsTFC.java
- src/main/java/net/dries007/tfc/api/capability/food/IFoodStatsTFC.java
- src/main/java/net/dries007/tfc/objects/LootTablesTFC.java
- src/main/java/net/dries007/tfc/objects/blocks/plants/BlockCreepingPlantTFC.java
- src/main/java/net/dries007/tfc/objects/blocks/plants/BlockPlantTFC.java
- src/main/java/net/dries007/tfc/objects/te/TEPitKiln.java
- src/main/java/net/dries007/tfc/world/classic/worldgen/WorldGenPlantTFC.java
Closes #43 
Closes #133 
Closes #235 
Closes #247 
Closes #255
> More bugfixing

- src/main/java/net/dries007/tfc/client/ClientEvents.java
- src/main/java/net/dries007/tfc/client/TFCGuiHandler.java
- src/main/java/net/dries007/tfc/client/gui/GuiScreenHorseInventoryTFC.java
- src/main/java/net/dries007/tfc/client/model/animal/ModelHorseTFC.java
- src/main/java/net/dries007/tfc/client/render/animal/RenderAbstractHorseTFC.java
- src/main/java/net/dries007/tfc/client/render/animal/RenderAnimalTFCFamiliarity.java
- src/main/java/net/dries007/tfc/client/render/animal/RenderHorseTFC.java
- src/main/java/net/dries007/tfc/objects/LootTablesTFC.java
- src/main/java/net/dries007/tfc/objects/container/ContainerHorseInventoryTFC.java
- src/main/java/net/dries007/tfc/objects/entity/EntitiesTFC.java
- src/main/java/net/dries007/tfc/objects/entity/ai/EntityAIRunAroundLikeCrazyTFC.java
- src/main/java/net/dries007/tfc/objects/entity/animal/AbstractChestHorseTFC.java
- src/main/java/net/dries007/tfc/objects/entity/animal/AbstractHorseTFC.java
- src/main/java/net/dries007/tfc/objects/entity/animal/EntityDonkeyTFC.java
- src/main/java/net/dries007/tfc/objects/entity/animal/EntityHorseTFC.java
- src/main/java/net/dries007/tfc/objects/entity/animal/EntityMuleTFC.java
- src/main/java/net/dries007/tfc/objects/entity/animal/EntityWolfTFC.java
- src/main/java/net/dries007/tfc/types/DefaultRecipes.java
- src/main/java/net/dries007/tfc/world/classic/biomes/BiomeTFC.java
Mostly vanilla like horses. Can be tamed only if enough familiarity.
One tricky moment at AbstractHorseTFC.openGUI, using BlockPos as custom data.
> Added Horses

- generateResources.py
- src/main/java/net/dries007/tfc/api/types/Rock.java
- src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java
- src/main/java/net/dries007/tfc/objects/blocks/stone/BlockRockSpike.java
- src/main/java/net/dries007/tfc/objects/blocks/stone/BlockRockVariant.java
- src/main/java/net/dries007/tfc/world/classic/ChunkGenTFC.java
- src/main/java/net/dries007/tfc/world/classic/mapgen/MapGenCavesTFC.java
- src/main/java/net/dries007/tfc/world/classic/worldgen/WorldGenFalls.java
- src/main/java/net/dries007/tfc/world/classic/worldgen/WorldGenSpikes.java
> Cave Decoration

- src/main/java/net/dries007/tfc/objects/blocks/wood/BlockSupport.java
- src/main/java/net/dries007/tfc/objects/entity/animal/EntityAnimalTFC.java
- src/main/java/net/dries007/tfc/objects/items/ceramics/ItemJug.java
> Another bug fixing PR

- src/main/java/net/dries007/tfc/world/classic/worldgen/WorldGenLooseRocks.java
- src/main/java/net/dries007/tfc/world/classic/worldgen/vein/VeinRegistry.java
- Improved performance over small ore generation
- Added a function in `VeinRegistry` so addons can register veins without overriding config file.
> Small improvements

- src/main/java/net/dries007/tfc/CommonEventHandler.java
- src/main/java/net/dries007/tfc/api/capability/food/FoodStatsTFC.java
- src/main/java/net/dries007/tfc/command/CommandSkill.java
- src/main/java/net/dries007/tfc/objects/blocks/stone/BlockRockRaw.java
- src/main/java/net/dries007/tfc/objects/blocks/stone/BlockRockVariant.java
- src/main/java/net/dries007/tfc/objects/items/ceramics/ItemSmallVessel.java
- src/main/java/net/dries007/tfc/objects/items/itemblock/ItemBlockBarrel.java
- src/main/java/net/dries007/tfc/objects/items/metal/ItemMetal.java
- src/main/java/net/dries007/tfc/objects/items/metal/ItemOreTFC.java
- src/main/java/net/dries007/tfc/objects/items/metal/ItemSmallOre.java
- src/main/java/net/dries007/tfc/objects/te/TELargeVessel.java
- src/main/java/net/dries007/tfc/objects/te/TEQuern.java
Again, each commit should describe what is fixed/enhanced.
> Some bugfixes and enhancements

- src/main/java/net/dries007/tfc/CommonEventHandler.java
- src/main/java/net/dries007/tfc/compat/crafttweaker/CTBarrel.java
- src/main/java/net/dries007/tfc/compat/crafttweaker/CTClayKnapping.java
- src/main/java/net/dries007/tfc/compat/crafttweaker/CTFireClayKnapping.java
- src/main/java/net/dries007/tfc/compat/crafttweaker/CTHeating.java
- src/main/java/net/dries007/tfc/compat/crafttweaker/CTLeatherKnapping.java
- src/main/java/net/dries007/tfc/compat/crafttweaker/CTLoom.java
- src/main/java/net/dries007/tfc/compat/crafttweaker/CTQuern.java
- src/main/java/net/dries007/tfc/compat/crafttweaker/CTWelding.java
- src/main/java/net/dries007/tfc/objects/blocks/BlockThatchBed.java
- src/main/java/net/dries007/tfc/objects/blocks/agriculture/BlockFruitTreeBranch.java
- src/main/java/net/dries007/tfc/objects/blocks/agriculture/BlockFruitTreeTrunk.java
- src/main/java/net/dries007/tfc/objects/blocks/devices/BlockBloomery.java
- src/main/java/net/dries007/tfc/objects/blocks/stone/BlockPathTFC.java
- src/main/java/net/dries007/tfc/objects/entity/animal/EntityAnimalTFC.java
- src/main/java/net/dries007/tfc/objects/te/TEBloomery.java
- src/main/java/net/dries007/tfc/util/calendar/ICalendarTickable.java
- Added missing nest box recipe (Closes TerraFirmaCraft#610).
- Fixed block updates near thatch bed breaking it (Closes TerraFirmaCraft#589).
- Hopefully fixed TerraFirmaCraft#581 by changing spawn checks.
- Bloomery structure now checks for replaceable materials instead of air (Closes TerraFirmaCraft#570).
- Fixed #611 
more fixes in newer commits (check their description for more info)
> Some bug fixes

- src/main/java/net/dries007/tfc/ConfigTFC.java
- src/main/java/net/dries007/tfc/client/gui/GuiBlastFurnace.java
- src/main/java/net/dries007/tfc/compat/crafttweaker/CTItemRegistry.java
- src/main/java/net/dries007/tfc/objects/blocks/devices/BlockBlastFurnace.java
- src/main/java/net/dries007/tfc/objects/items/metal/ItemOreTFC.java
- src/main/java/net/dries007/tfc/objects/te/TEBlastFurnace.java
- src/main/java/net/dries007/tfc/objects/te/TEBloomery.java
- src/main/java/net/dries007/tfc/util/OreDictionaryHelper.java
- src/main/java/net/dries007/tfc/util/fuel/Fuel.java
- src/main/java/net/dries007/tfc/util/fuel/FuelManager.java
> Changes in blast furnace and fuel manager

- src/main/java/net/dries007/tfc/CommonEventHandler.java
- src/main/java/net/dries007/tfc/api/capability/player/IPlayerData.java
- src/main/java/net/dries007/tfc/api/capability/player/PlayerDataHandler.java
- src/main/java/net/dries007/tfc/client/gui/GuiKnapping.java
- src/main/java/net/dries007/tfc/objects/blocks/BlockPlacedHide.java
- src/main/java/net/dries007/tfc/objects/blocks/wood/BlockLogTFC.java
- src/main/java/net/dries007/tfc/objects/container/ContainerKnapping.java
- src/main/java/net/dries007/tfc/objects/te/TELargeVessel.java
> And more bug fixes!
